apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.vote_app.name }}
spec:
  replicas: {{ .Values.vote_app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.vote_app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.vote_app.name }}
    spec:
      containers:
        - name: {{ .Values.vote_app.name }}
          image: {{ .Values.vote_app.image }}
          ports:
            - containerPort: {{ .Values.vote_app.port }}

