apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.vote_app.name }}
spec:
  selector:
    app: {{ .Values.vote_app.name }}
  ports:
    - name: http
      port: {{ .Values.vote_app.port }}
      targetPort: {{ .Values.vote_app.port }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.name }}
spec:
  selector:
    app: {{ .Values.nginx.name }}
  ports:
    - name: http
      port: {{ .Values.nginx.port }}
      targetPort: {{ .Values.nginx.port }}
  type: NodePort
