apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgres.configMapName }}
data:
  POSTGRES_USER: {{ .Values.postgres.envSecret.POSTGRES_USER }}
  POSTGRES_DB: {{ .Values.postgres.envSecret.POSTGRES_DB }}
  DB_HOST: {{ .Values.postgres.serviceName }}
