Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"

  config.vm.define "control_plane" do |control_plane|
    control_plane.vm.hostname = "control-plane"
    control_plane.vm.network "private_network", ip: "192.168.56.11"

    control_plane.vm.network "forwarded_port",
      guest: 30080, host: 8080, auto_correct: true

    control_plane.vm.network "forwarded_port",
      guest: 30081, host: 8081, auto_correct: true

    control_plane.vm.provider :libvirt do |libvirt|
      libvirt.memory = 2048
      libvirt.cpus = 2
    end
  end

  config.vm.define "worker" do |worker|
    worker.vm.hostname = "worker"
    worker.vm.network "private_network", ip: "192.168.56.12"

    worker.vm.provider :libvirt do |libvirt|
      libvirt.memory = 2048
      libvirt.cpus = 2
    end
  end
end

