version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    image: Faithbound_Legion:v1
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:16-bookworm
    environment:
      POSTGRES_USER: Omnissiah
      POSTGRES_PASSWORD: 40000
      POSTGRES_DB: Vox_Servitor_Ordo_Database

  nginx:
    image: nginx
    