FROM ubuntu:24.04

RUN apt-get update && apt-get install -y curl git sudo openssh-client && \
    apt-get clean && \
    rm -rf /var/lib/apt/* && \
    rm -rf /var/cache/apt/*

WORKDIR /github

COPY ../github_runner

ENTRYPOINT ["./run.sh"]
