
services:
  postgress:
    image: postgres:16-bookworm
    container_name: Machine_Spirit
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: Omnissiah
      POSTGRES_PASSWORD: "ninja"
      POSTGRES_DB: Servitor_ID0978
    volumes:
      - pg_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h 127.0.0.1 || exit 1"]
      interval: 3s
      timeout: 3s
      retries: 20

  vote_app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: faithbound-legion:v1
    container_name: The_Sigil_of_Judgment
    ports:
      - "8000:8000"
    command: bash -c "python manage.py migrate && gunicorn mysite.wsgi:application -c config/gunicorn_conf.py"
    depends_on:
      postgress:
        condition: service_healthy

  nginx:
    image: nginx
    container_name: reverse_proxy
    ports:
      - "8080:80"
    volumes:
    - ../config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - vote_app

volumes:
  pg_data: