- name: Install Prod Helm Chart
  shell: helm install prod-myapp . --wait --timeout 3m --atomic
  args:
    chdir: /home/vagrant/Django_final_project/kubernetes/production_helm_chart
    executable: /bin/bash
  become: false
