# Generated by Django 5.2.6 on 2025-09-29 08:07
from django.db import migrations
import datetime
from datetime import timezone


def create_default_question(apps, schema_editor):
    Question = apps.get_model('polls', 'Question')
    Choice = apps.get_model('polls', 'Choice')

    q = Question.objects.create(
        question_text="Do you pledge your faith in the Emperor of Mankind?",
        pub_date=datetime.datetime.utcnow().replace(tzinfo=timezone.utc)
    )
    q.choice_set.create(choice_text="yes", votes=0)
    q.choice_set.create(choice_text="no", votes=0)

class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_question),
    ]

